# Generated by Django 4.1.7 on 2023-05-03 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, null=True)),
                ('lastname', models.CharField(max_length=100, null=True)),
                ('guaranter_time', models.PositiveSmallIntegerField(blank=True, default=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Loanamount', models.FloatField()),
                ('Intrest', models.FloatField()),
                ('PayPerInstallment', models.FloatField()),
                ('Installment_time', models.PositiveSmallIntegerField()),
                ('Guaranter_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Loaner', 'Loaner'), ('Paid', 'Paid')], max_length=50, null=True)),
                ('customerid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loan.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Installment_time', models.PositiveSmallIntegerField(default=0)),
                ('Amountpaid', models.FloatField()),
                ('PaidDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('Loanid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loan.loan')),
            ],
        ),
    ]
