# Generated by Django 4.1.7 on 2023-05-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='Guaranter_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='card_num',
            field=models.PositiveSmallIntegerField(default=0.08333333333333333),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='Guaranter_id',
            field=models.PositiveSmallIntegerField(default=0.08333333333333333),
            preserve_default=False,
        ),
    ]
