# Generated by Django 4.1.7 on 2023-05-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_remove_loan_guaranter_name_customer_card_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='card_num',
            field=models.IntegerField(),
        ),
    ]
