# Generated by Django 4.1.7 on 2023-05-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_alter_customer_card_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='card_num',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
