# Generated by Django 4.1.7 on 2023-05-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0006_loan_totalpaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='TotalPaid',
            field=models.FloatField(null=True),
        ),
    ]
