# Generated by Django 4.1.7 on 2023-05-03 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0007_alter_loan_totalpaid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bill',
            new_name='LoanRecord',
        ),
    ]
